### ISSUE TITLE
Error: Unexpected core_pattern

### ISSUE THREAD

**Issue by gknisely** [mapbox/logbt#37]
I am seeing the following error while trying to use logbt.  Unexpected core_pattern: /tmp/logbt-coredumps/core.%p  I am running setup with sudo, but I don't think it is working correctly as if I sleep my bash script, ssh to the instance, run sudo logbt --setup manually, and then run my binary with logbt everything is fine.  However, via the script I see the error noted above.  Could this be related to running this on AWS spot instances?  Please advise.

**Comment by springmeyer** [comment]
@gknisely my guess is that you are running in docker and there are other tasks on your same host that are modifying the core_pattern. So, the problem is not that `logbt --setup` is not working, but rather that some other process is running `logbt` (likely version v1.x) which sets ` /tmp/logbt-coredumps/core.%p`. Starting in v1.4.0 logbt started using/setting/expecting ` /tmp/logbt-coredumps/core.%p.%E`.

So, to workaround you'll need to assess whether to downgrade your logbt version to v1.2.0 or whether to find the other tasks that are running v1.2.0 and upgrade them to v2.x.
